/* 
 * The MIT License
 *
 * Copyright 2014 Key Bridge Global LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package us.gov.dod.standard.ssrf._3_1.metadata.lists;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import us.gov.dod.standard.ssrf._3_1.assignment.Link;

/**
 * Enumerated values for fields using the ListCFN type.
 * <p>
 * Used in {@link Link}
 * <p>
 * @author Key Bridge Global LLC <developer@keybridgeglobal.com>
 * @version SSRF 3.1.0, 10/01/2014
 */
@XmlType(name = "ListCFN")
@XmlEnum
public enum ListCFN {

  UNKNOWN("UNKNOWN"),
  @XmlEnumValue("AIR OPS")
  AIR_OPS("AIR OPS"),
  @XmlEnumValue("AIR OPS - AIR/AIR COMMS")
  AIR_OPS___AIR_AIR_COMMS("AIR OPS - AIR/AIR COMMS"),
  @XmlEnumValue("AIR OPS - AIR/AIR COMMS - A-EPLRS")
  AIR_OPS___AIR_AIR_COMMS___A_EPLRS("AIR OPS - AIR/AIR COMMS - A-EPLRS"),
  @XmlEnumValue("AIR OPS - AIR/AIR COMMS - AIR DEFENSE/INTERCEPT")
  AIR_OPS___AIR_AIR_COMMS___AIR_DEFENSE_INTERCEPT("AIR OPS - AIR/AIR COMMS - AIR DEFENSE/INTERCEPT"),
  @XmlEnumValue("AIR OPS - AIR/AIR COMMS - BLUE ANGELS")
  AIR_OPS___AIR_AIR_COMMS___BLUE_ANGELS("AIR OPS - AIR/AIR COMMS - BLUE ANGELS"),
  @XmlEnumValue("AIR OPS - AIR/AIR COMMS - HAVE QUICK")
  AIR_OPS___AIR_AIR_COMMS___HAVE_QUICK("AIR OPS - AIR/AIR COMMS - HAVE QUICK"),
  @XmlEnumValue("AIR OPS - AIR/AIR COMMS - SATURN")
  AIR_OPS___AIR_AIR_COMMS___SATURN("AIR OPS - AIR/AIR COMMS - SATURN"),
  @XmlEnumValue("AIR OPS - AIR/AIR COMMS - INSTRUCTOR/STUDENT TRAINING")
  AIR_OPS___AIR_AIR_COMMS___INSTRUCTOR_STUDENT_TRAINING("AIR OPS - AIR/AIR COMMS - INSTRUCTOR/STUDENT TRAINING"),
  @XmlEnumValue("AIR OPS - AIR/AIR COMMS - INTERPLANE")
  AIR_OPS___AIR_AIR_COMMS___INTERPLANE("AIR OPS - AIR/AIR COMMS - INTERPLANE"),
  @XmlEnumValue("AIR OPS - AIR/AIR COMMS - PILOT-TO-PILOT")
  AIR_OPS___AIR_AIR_COMMS___PILOT_TO_PILOT("AIR OPS - AIR/AIR COMMS - PILOT-TO-PILOT"),
  @XmlEnumValue("AIR OPS - AIR/AIR COMMS - REFUELING")
  AIR_OPS___AIR_AIR_COMMS___REFUELING("AIR OPS - AIR/AIR COMMS - REFUELING"),
  @XmlEnumValue("AIR OPS - AIR/AIR COMMS - THUNDERBIRDS")
  AIR_OPS___AIR_AIR_COMMS___THUNDERBIRDS("AIR OPS - AIR/AIR COMMS - THUNDERBIRDS"),
  @XmlEnumValue("AIR OPS - AIR/GROUND/AIR COMMS")
  AIR_OPS___AIR_GROUND_AIR_COMMS("AIR OPS - AIR/GROUND/AIR COMMS"),
  @XmlEnumValue("AIR OPS - AIR/GROUND/AIR COMMS - AIR DEFENSE/INTERCEPT")
  AIR_OPS___AIR_GROUND_AIR_COMMS___AIR_DEFENSE_INTERCEPT("AIR OPS - AIR/GROUND/AIR COMMS - AIR DEFENSE/INTERCEPT"),
  @XmlEnumValue("AIR OPS - AIR/GROUND/AIR COMMS - BROADCAST")
  AIR_OPS___AIR_GROUND_AIR_COMMS___BROADCAST("AIR OPS - AIR/GROUND/AIR COMMS - BROADCAST"),
  @XmlEnumValue("AIR OPS - AIR/GROUND/AIR COMMS - COMMAND POST")
  AIR_OPS___AIR_GROUND_AIR_COMMS___COMMAND_POST("AIR OPS - AIR/GROUND/AIR COMMS - COMMAND POST"),
  @XmlEnumValue("AIR OPS - AIR/GROUND/AIR COMMS - FLIGHT FOLLOWING")
  AIR_OPS___AIR_GROUND_AIR_COMMS___FLIGHT_FOLLOWING("AIR OPS - AIR/GROUND/AIR COMMS - FLIGHT FOLLOWING"),
  @XmlEnumValue("AIR OPS - AIR/GROUND/AIR COMMS - GOLDEN KNIGHTS")
  AIR_OPS___AIR_GROUND_AIR_COMMS___GOLDEN_KNIGHTS("AIR OPS - AIR/GROUND/AIR COMMS - GOLDEN KNIGHTS"),
  @XmlEnumValue("AIR OPS - AIR/GROUND/AIR COMMS - HAVE QUICK")
  AIR_OPS___AIR_GROUND_AIR_COMMS___HAVE_QUICK("AIR OPS - AIR/GROUND/AIR COMMS - HAVE QUICK"),
  @XmlEnumValue("AIR OPS - AIR/GROUND/AIR COMMS - SATURN")
  AIR_OPS___AIR_GROUND_AIR_COMMS___SATURN("AIR OPS - AIR/GROUND/AIR COMMS - SATURN"),
  @XmlEnumValue("AIR OPS - AIR/GROUND/AIR COMMS - PILOT-TO-DISPATCHER")
  AIR_OPS___AIR_GROUND_AIR_COMMS___PILOT_TO_DISPATCHER("AIR OPS - AIR/GROUND/AIR COMMS - PILOT-TO-DISPATCHER"),
  @XmlEnumValue("AIR OPS - AIR/GROUND/AIR COMMS - PILOT-TO-METRO")
  AIR_OPS___AIR_GROUND_AIR_COMMS___PILOT_TO_METRO("AIR OPS - AIR/GROUND/AIR COMMS - PILOT-TO-METRO"),
  @XmlEnumValue("AIR OPS - AIR/GROUND/AIR COMMS - SQUADRON/WING COMMON")
  AIR_OPS___AIR_GROUND_AIR_COMMS___SQUADRON_WING_COMMON("AIR OPS - AIR/GROUND/AIR COMMS - SQUADRON/WING COMMON"),
  @XmlEnumValue("AIR OPS - AIR/GROUND/AIR COMMS - SOF")
  AIR_OPS___AIR_GROUND_AIR_COMMS___SOF("AIR OPS - AIR/GROUND/AIR COMMS - SOF"),
  @XmlEnumValue("AIR OPS - AIR/GROUND/AIR COMMS - TRAINING")
  AIR_OPS___AIR_GROUND_AIR_COMMS___TRAINING("AIR OPS - AIR/GROUND/AIR COMMS - TRAINING"),
  @XmlEnumValue("AIR OPS - AIR TRAFFIC CONTROL")
  AIR_OPS___AIR_TRAFFIC_CONTROL("AIR OPS - AIR TRAFFIC CONTROL"),
  @XmlEnumValue("AIR OPS - AIR TRAFFIC CONTROL - APPROACH CONTROL")
  AIR_OPS___AIR_TRAFFIC_CONTROL___APPROACH_CONTROL("AIR OPS - AIR TRAFFIC CONTROL - APPROACH CONTROL"),
  @XmlEnumValue("AIR OPS - AIR TRAFFIC CONTROL - ATIS")
  AIR_OPS___AIR_TRAFFIC_CONTROL___ATIS("AIR OPS - AIR TRAFFIC CONTROL - ATIS"),
  @XmlEnumValue("AIR OPS - AIR TRAFFIC CONTROL - CLEARANCE DELIVERY")
  AIR_OPS___AIR_TRAFFIC_CONTROL___CLEARANCE_DELIVERY("AIR OPS - AIR TRAFFIC CONTROL - CLEARANCE DELIVERY"),
  @XmlEnumValue("AIR OPS - AIR TRAFFIC CONTROL - DBRITE")
  AIR_OPS___AIR_TRAFFIC_CONTROL___DBRITE("AIR OPS - AIR TRAFFIC CONTROL - DBRITE"),
  @XmlEnumValue("AIR OPS - AIR TRAFFIC CONTROL - DEPARTURE CONTROL")
  AIR_OPS___AIR_TRAFFIC_CONTROL___DEPARTURE_CONTROL("AIR OPS - AIR TRAFFIC CONTROL - DEPARTURE CONTROL"),
  @XmlEnumValue("AIR OPS - AIR TRAFFIC CONTROL - FEEDER CONTROL")
  AIR_OPS___AIR_TRAFFIC_CONTROL___FEEDER_CONTROL("AIR OPS - AIR TRAFFIC CONTROL - FEEDER CONTROL"),
  @XmlEnumValue("AIR OPS - AIR TRAFFIC CONTROL - FLIGHT INSPECTION")
  AIR_OPS___AIR_TRAFFIC_CONTROL___FLIGHT_INSPECTION("AIR OPS - AIR TRAFFIC CONTROL - FLIGHT INSPECTION"),
  @XmlEnumValue("AIR OPS - AIR TRAFFIC CONTROL - GCA")
  AIR_OPS___AIR_TRAFFIC_CONTROL___GCA("AIR OPS - AIR TRAFFIC CONTROL - GCA"),
  @XmlEnumValue("AIR OPS - AIR TRAFFIC CONTROL - GROUND CONTROL")
  AIR_OPS___AIR_TRAFFIC_CONTROL___GROUND_CONTROL("AIR OPS - AIR TRAFFIC CONTROL - GROUND CONTROL"),
  @XmlEnumValue("AIR OPS - AIR TRAFFIC CONTROL - LOCAL CONTROL")
  AIR_OPS___AIR_TRAFFIC_CONTROL___LOCAL_CONTROL("AIR OPS - AIR TRAFFIC CONTROL - LOCAL CONTROL"),
  @XmlEnumValue("AIR OPS - AIR TRAFFIC CONTROL - TOWER")
  AIR_OPS___AIR_TRAFFIC_CONTROL___TOWER("AIR OPS - AIR TRAFFIC CONTROL - TOWER"),
  @XmlEnumValue("AIR OPS - EXECUTIVE")
  AIR_OPS___EXECUTIVE("AIR OPS - EXECUTIVE"),
  @XmlEnumValue("AIR OPS - EXECUTIVE - AIR FORCE ONE")
  AIR_OPS___EXECUTIVE___AIR_FORCE_ONE("AIR OPS - EXECUTIVE - AIR FORCE ONE"),
  @XmlEnumValue("AIR OPS - EXECUTIVE - AIRBORNE COMMAND CENTER")
  AIR_OPS___EXECUTIVE___AIRBORNE_COMMAND_CENTER("AIR OPS - EXECUTIVE - AIRBORNE COMMAND CENTER"),
  @XmlEnumValue("AIR OPS - EXECUTIVE - GENERAL OFFICER SUPPORT")
  AIR_OPS___EXECUTIVE___GENERAL_OFFICER_SUPPORT("AIR OPS - EXECUTIVE - GENERAL OFFICER SUPPORT"),
  @XmlEnumValue("AIR OPS - EXECUTIVE - ERCS")
  AIR_OPS___EXECUTIVE___ERCS("AIR OPS - EXECUTIVE - ERCS"),
  @XmlEnumValue("AIR OPS - EXECUTIVE - MYSTIC STAR")
  AIR_OPS___EXECUTIVE___MYSTIC_STAR("AIR OPS - EXECUTIVE - MYSTIC STAR"),
  @XmlEnumValue("AIR OPS - EXECUTIVE - NAOC (National Airborne OPS Center)")
  AIR_OPS___EXECUTIVE___NAOC__NATIONAL_AIRBORNE_OPS_CENTER__("AIR OPS - EXECUTIVE - NAOC (National Airborne OPS Center)"),
  @XmlEnumValue("AIR OPS - EXECUTIVE - NORAD")
  AIR_OPS___EXECUTIVE___NORAD("AIR OPS - EXECUTIVE - NORAD"),
  @XmlEnumValue("AIR OPS - EXECUTIVE - WHCA (White House COMMS Agency)")
  AIR_OPS___EXECUTIVE___WHCA__WHITE_HOUSE_COMMS_AGENCY__("AIR OPS - EXECUTIVE - WHCA (White House COMMS Agency)"),
  @XmlEnumValue("AIR OPS - FLIGHT TEST")
  AIR_OPS___FLIGHT_TEST("AIR OPS - FLIGHT TEST"),
  @XmlEnumValue("AIR OPS - NAVAIDS")
  AIR_OPS___NAVAIDS("AIR OPS - NAVAIDS"),
  @XmlEnumValue("AIR OPS - NAVAIDS - AIR ROUTE SURVEILLANCE RADAR")
  AIR_OPS___NAVAIDS___AIR_ROUTE_SURVEILLANCE_RADAR("AIR OPS - NAVAIDS - AIR ROUTE SURVEILLANCE RADAR"),
  @XmlEnumValue("AIR OPS - NAVAIDS - AIRPORT SURVEILLANCE RADAR")
  AIR_OPS___NAVAIDS___AIRPORT_SURVEILLANCE_RADAR("AIR OPS - NAVAIDS - AIRPORT SURVEILLANCE RADAR"),
  @XmlEnumValue("AIR OPS - NAVAIDS - BEACON")
  AIR_OPS___NAVAIDS___BEACON("AIR OPS - NAVAIDS - BEACON"),
  @XmlEnumValue("AIR OPS - NAVAIDS - ETCAS")
  AIR_OPS___NAVAIDS___ETCAS("AIR OPS - NAVAIDS - ETCAS"),
  @XmlEnumValue("AIR OPS - NAVAIDS - IFF/SIF")
  AIR_OPS___NAVAIDS___IFF_SIF("AIR OPS - NAVAIDS - IFF/SIF"),
  @XmlEnumValue("AIR OPS - NAVAIDS - ILS")
  AIR_OPS___NAVAIDS___ILS("AIR OPS - NAVAIDS - ILS"),
  @XmlEnumValue("AIR OPS - NAVAIDS - MLS")
  AIR_OPS___NAVAIDS___MLS("AIR OPS - NAVAIDS - MLS"),
  @XmlEnumValue("AIR OPS - NAVAIDS - PAR")
  AIR_OPS___NAVAIDS___PAR("AIR OPS - NAVAIDS - PAR"),
  @XmlEnumValue("AIR OPS - NAVAIDS - RF TAGS")
  AIR_OPS___NAVAIDS___RF_TAGS("AIR OPS - NAVAIDS - RF TAGS"),
  @XmlEnumValue("AIR OPS - NAVAIDS - TACAN")
  AIR_OPS___NAVAIDS___TACAN("AIR OPS - NAVAIDS - TACAN"),
  @XmlEnumValue("AIR OPS - NAVAIDS - TCAS")
  AIR_OPS___NAVAIDS___TCAS("AIR OPS - NAVAIDS - TCAS"),
  @XmlEnumValue("AIR OPS - NAVAIDS - VOR")
  AIR_OPS___NAVAIDS___VOR("AIR OPS - NAVAIDS - VOR"),
  @XmlEnumValue("AIR OPS - NAVAIDS - VORTAC")
  AIR_OPS___NAVAIDS___VORTAC("AIR OPS - NAVAIDS - VORTAC"),
  @XmlEnumValue("AIR OPS - NAVAIDS - WEATHER RADAR")
  AIR_OPS___NAVAIDS___WEATHER_RADAR("AIR OPS - NAVAIDS - WEATHER RADAR"),
  @XmlEnumValue("AIR OPS - TELECOMMAND")
  AIR_OPS___TELECOMMAND("AIR OPS - TELECOMMAND"),
  @XmlEnumValue("AIR OPS - TELECOMMAND - COMMAND DESTRUCT/TERMINATION")
  AIR_OPS___TELECOMMAND___COMMAND_DESTRUCT_TERMINATION("AIR OPS - TELECOMMAND - COMMAND DESTRUCT/TERMINATION"),
  @XmlEnumValue("AIR OPS - TELECOMMAND - DRONE CONTROL")
  AIR_OPS___TELECOMMAND___DRONE_CONTROL("AIR OPS - TELECOMMAND - DRONE CONTROL"),
  @XmlEnumValue("AIR OPS - TELECOMMAND - MICROWAVE DATA LINK")
  AIR_OPS___TELECOMMAND___MICROWAVE_DATA_LINK("AIR OPS - TELECOMMAND - MICROWAVE DATA LINK"),
  @XmlEnumValue("AIR OPS - TELECOMMAND - TMGS")
  AIR_OPS___TELECOMMAND___TMGS("AIR OPS - TELECOMMAND - TMGS"),
  @XmlEnumValue("AIR OPS - TELECOMMAND - TOSS")
  AIR_OPS___TELECOMMAND___TOSS("AIR OPS - TELECOMMAND - TOSS"),
  @XmlEnumValue("AIR OPS - UAV")
  AIR_OPS___UAV("AIR OPS - UAV"),
  @XmlEnumValue("AIR OPS - TRAINING")
  AIR_OPS___TRAINING("AIR OPS - TRAINING"),
  @XmlEnumValue("AIR OPS - TARGET ACQUISITION")
  AIR_OPS___TARGET_ACQUISITION("AIR OPS - TARGET ACQUISITION"),
  @XmlEnumValue("AIR OPS - TARGET ACQUISITION - LONGBOW")
  AIR_OPS___TARGET_ACQUISITION___LONGBOW("AIR OPS - TARGET ACQUISITION - LONGBOW"),
  @XmlEnumValue("AIR OPS - TARGET ACQUISITION - MISSILE")
  AIR_OPS___TARGET_ACQUISITION___MISSILE("AIR OPS - TARGET ACQUISITION - MISSILE"),
  @XmlEnumValue("AIR OPS - APPROACH/DEPARTURE CONTROL")
  AIR_OPS___APPROACH_DEPARTURE_CONTROL("AIR OPS - APPROACH/DEPARTURE CONTROL"),
  @XmlEnumValue("GROUND OPS")
  GROUND_OPS("GROUND OPS"),
  @XmlEnumValue("GROUND OPS - AIR DEFENSE")
  GROUND_OPS___AIR_DEFENSE("GROUND OPS - AIR DEFENSE"),
  @XmlEnumValue("GROUND OPS - AIR DEFENSE - ARTILLERY")
  GROUND_OPS___AIR_DEFENSE___ARTILLERY("GROUND OPS - AIR DEFENSE - ARTILLERY"),
  @XmlEnumValue("GROUND OPS - AIR DEFENSE - AVENGER-STC")
  GROUND_OPS___AIR_DEFENSE___AVENGER_STC("GROUND OPS - AIR DEFENSE - AVENGER-STC"),
  @XmlEnumValue("GROUND OPS - AIR DEFENSE - FAADC2")
  GROUND_OPS___AIR_DEFENSE___FAADC_2("GROUND OPS - AIR DEFENSE - FAADC2"),
  @XmlEnumValue("GROUND OPS - AIR DEFENSE - LINEBACKER")
  GROUND_OPS___AIR_DEFENSE___LINEBACKER("GROUND OPS - AIR DEFENSE - LINEBACKER"),
  @XmlEnumValue("GROUND OPS - AIR DEFENSE - PATRIOT")
  GROUND_OPS___AIR_DEFENSE___PATRIOT("GROUND OPS - AIR DEFENSE - PATRIOT"),
  @XmlEnumValue("GROUND OPS - AIR DEFENSE - SENTINEL")
  GROUND_OPS___AIR_DEFENSE___SENTINEL("GROUND OPS - AIR DEFENSE - SENTINEL"),
  @XmlEnumValue("GROUND OPS - ENGINEERS")
  GROUND_OPS___ENGINEERS("GROUND OPS - ENGINEERS"),
  @XmlEnumValue("GROUND OPS - ENGINEERS - GRIZZLY")
  GROUND_OPS___ENGINEERS___GRIZZLY("GROUND OPS - ENGINEERS - GRIZZLY"),
  @XmlEnumValue("GROUND OPS - ENGINEERS - M93A1 FOX")
  GROUND_OPS___ENGINEERS___M_93_A_1_FOX("GROUND OPS - ENGINEERS - M93A1 FOX"),
  @XmlEnumValue("GROUND OPS - ENGINEERS - WOLVERINE")
  GROUND_OPS___ENGINEERS___WOLVERINE("GROUND OPS - ENGINEERS - WOLVERINE"),
  @XmlEnumValue("GROUND OPS - ARTILLERY")
  GROUND_OPS___ARTILLERY("GROUND OPS - ARTILLERY"),
  @XmlEnumValue("GROUND OPS - ARTILLERY - AQF")
  GROUND_OPS___ARTILLERY___AQF("GROUND OPS - ARTILLERY - AQF"),
  @XmlEnumValue("GROUND OPS - ARTILLERY - LLDR")
  GROUND_OPS___ARTILLERY___LLDR("GROUND OPS - ARTILLERY - LLDR"),
  @XmlEnumValue("GROUND OPS - ARTILLERY - MLRS")
  GROUND_OPS___ARTILLERY___MLRS("GROUND OPS - ARTILLERY - MLRS"),
  @XmlEnumValue("GROUND OPS - BATTLE COMMAND")
  GROUND_OPS___BATTLE_COMMAND("GROUND OPS - BATTLE COMMAND"),
  @XmlEnumValue("GROUND OPS - BATTLE COMMAND - A2C2S")
  GROUND_OPS___BATTLE_COMMAND___A_2_C_2_S("GROUND OPS - BATTLE COMMAND - A2C2S"),
  @XmlEnumValue("GROUND OPS - BATTLE COMMAND - A-EPLRS (SADL)")
  GROUND_OPS___BATTLE_COMMAND___A_EPLRS__SADL__("GROUND OPS - BATTLE COMMAND - A-EPLRS (SADL)"),
  @XmlEnumValue("GROUND OPS - BATTLE COMMAND - CTT")
  GROUND_OPS___BATTLE_COMMAND___CTT("GROUND OPS - BATTLE COMMAND - CTT"),
  @XmlEnumValue("GROUND OPS - BATTLE COMMAND - EPLRS")
  GROUND_OPS___BATTLE_COMMAND___EPLRS("GROUND OPS - BATTLE COMMAND - EPLRS"),
  @XmlEnumValue("GROUND OPS - BATTLE COMMAND - LAND WARRIOR")
  GROUND_OPS___BATTLE_COMMAND___LAND_WARRIOR("GROUND OPS - BATTLE COMMAND - LAND WARRIOR"),
  @XmlEnumValue("GROUND OPS - BATTLE COMMAND - NTDR")
  GROUND_OPS___BATTLE_COMMAND___NTDR("GROUND OPS - BATTLE COMMAND - NTDR"),
  @XmlEnumValue("GROUND OPS - BATTLE COMMAND - SCAMP")
  GROUND_OPS___BATTLE_COMMAND___SCAMP("GROUND OPS - BATTLE COMMAND - SCAMP"),
  @XmlEnumValue("GROUND OPS - BATTLE COMMAND - SINCGARS")
  GROUND_OPS___BATTLE_COMMAND___SINCGARS("GROUND OPS - BATTLE COMMAND - SINCGARS"),
  @XmlEnumValue("GROUND OPS - BATTLE COMMAND - SINCGARS-ASIP")
  GROUND_OPS___BATTLE_COMMAND___SINCGARS_ASIP("GROUND OPS - BATTLE COMMAND - SINCGARS-ASIP"),
  @XmlEnumValue("GROUND OPS - BATTLE COMMAND - WIN-T")
  GROUND_OPS___BATTLE_COMMAND___WIN_T("GROUND OPS - BATTLE COMMAND - WIN-T"),
  @XmlEnumValue("GROUND OPS - CAVALRY")
  GROUND_OPS___CAVALRY("GROUND OPS - CAVALRY"),
  @XmlEnumValue("GROUND OPS - CAVALRY - STRIKER II")
  GROUND_OPS___CAVALRY___STRIKER_II("GROUND OPS - CAVALRY - STRIKER II"),
  @XmlEnumValue("GROUND OPS - CLOSE AIR SUPPORT (CAS)")
  GROUND_OPS___CLOSE_AIR_SUPPORT__CAS__("GROUND OPS - CLOSE AIR SUPPORT (CAS)"),
  @XmlEnumValue("GROUND OPS - COMBAT CONTROL TEAM")
  GROUND_OPS___COMBAT_CONTROL_TEAM("GROUND OPS - COMBAT CONTROL TEAM"),
  @XmlEnumValue("GROUND OPS - COMMAND POST")
  GROUND_OPS___COMMAND_POST("GROUND OPS - COMMAND POST"),
  @XmlEnumValue("GROUND OPS - ELECTRONIC WARFARE")
  GROUND_OPS___ELECTRONIC_WARFARE("GROUND OPS - ELECTRONIC WARFARE"),
  @XmlEnumValue("GROUND OPS - ELECTRONIC WARFARE - ACS")
  GROUND_OPS___ELECTRONIC_WARFARE___ACS("GROUND OPS - ELECTRONIC WARFARE - ACS"),
  @XmlEnumValue("GROUND OPS - ELECTRONIC WARFARE - AHFEWS")
  GROUND_OPS___ELECTRONIC_WARFARE___AHFEWS("GROUND OPS - ELECTRONIC WARFARE - AHFEWS"),
  @XmlEnumValue("GROUND OPS - ELECTRONIC WARFARE - ARL")
  GROUND_OPS___ELECTRONIC_WARFARE___ARL("GROUND OPS - ELECTRONIC WARFARE - ARL"),
  @XmlEnumValue("GROUND OPS - ELECTRONIC WARFARE - IEWCS")
  GROUND_OPS___ELECTRONIC_WARFARE___IEWCS("GROUND OPS - ELECTRONIC WARFARE - IEWCS"),
  @XmlEnumValue("GROUND OPS - ELECTRONIC WARFARE - LMRDFS")
  GROUND_OPS___ELECTRONIC_WARFARE___LMRDFS("GROUND OPS - ELECTRONIC WARFARE - LMRDFS"),
  @XmlEnumValue("GROUND OPS - ELECTRONIC WARFARE - TACJAM")
  GROUND_OPS___ELECTRONIC_WARFARE___TACJAM("GROUND OPS - ELECTRONIC WARFARE - TACJAM"),
  @XmlEnumValue("GROUND OPS - ELECTRONIC WARFARE - TEAMMATE")
  GROUND_OPS___ELECTRONIC_WARFARE___TEAMMATE("GROUND OPS - ELECTRONIC WARFARE - TEAMMATE"),
  @XmlEnumValue("GROUND OPS - ELECTRONIC WARFARE - TRACKWOLF")
  GROUND_OPS___ELECTRONIC_WARFARE___TRACKWOLF("GROUND OPS - ELECTRONIC WARFARE - TRACKWOLF"),
  @XmlEnumValue("GROUND OPS - FIRE SUPPORT")
  GROUND_OPS___FIRE_SUPPORT("GROUND OPS - FIRE SUPPORT"),
  @XmlEnumValue("GROUND OPS - FIRE SUPPORT - AFATDS")
  GROUND_OPS___FIRE_SUPPORT___AFATDS("GROUND OPS - FIRE SUPPORT - AFATDS"),
  @XmlEnumValue("GROUND OPS - FIRE SUPPORT - ARTILLERY")
  GROUND_OPS___FIRE_SUPPORT___ARTILLERY("GROUND OPS - FIRE SUPPORT - ARTILLERY"),
  @XmlEnumValue("GROUND OPS - FIRE SUPPORT - CLOSE AIR SUPPORT (CAS)")
  GROUND_OPS___FIRE_SUPPORT___CLOSE_AIR_SUPPORT__CAS__("GROUND OPS - FIRE SUPPORT - CLOSE AIR SUPPORT (CAS)"),
  @XmlEnumValue("GROUND OPS - FIRE SUPPORT - MFCS")
  GROUND_OPS___FIRE_SUPPORT___MFCS("GROUND OPS - FIRE SUPPORT - MFCS"),
  @XmlEnumValue("GROUND OPS - FORWARD AIR CONTROL POST")
  GROUND_OPS___FORWARD_AIR_CONTROL_POST("GROUND OPS - FORWARD AIR CONTROL POST"),
  @XmlEnumValue("GROUND OPS - GROUND INTERDICTION")
  GROUND_OPS___GROUND_INTERDICTION("GROUND OPS - GROUND INTERDICTION"),
  @XmlEnumValue("GROUND OPS - GROUND INTERDICTION - CIWS")
  GROUND_OPS___GROUND_INTERDICTION___CIWS("GROUND OPS - GROUND INTERDICTION - CIWS"),
  @XmlEnumValue("GROUND OPS - GROUND INTERDICTION - GBCS-L")
  GROUND_OPS___GROUND_INTERDICTION___GBCS_L("GROUND OPS - GROUND INTERDICTION - GBCS-L"),
  @XmlEnumValue("GROUND OPS - GROUND INTERDICTION - GSR")
  GROUND_OPS___GROUND_INTERDICTION___GSR("GROUND OPS - GROUND INTERDICTION - GSR"),
  @XmlEnumValue("GROUND OPS - GROUND INTERDICTION - I-REMBASS")
  GROUND_OPS___GROUND_INTERDICTION___I_REMBASS("GROUND OPS - GROUND INTERDICTION - I-REMBASS"),
  @XmlEnumValue("GROUND OPS - GROUND INTERDICTION - TRAILBLAZER")
  GROUND_OPS___GROUND_INTERDICTION___TRAILBLAZER("GROUND OPS - GROUND INTERDICTION - TRAILBLAZER"),
  @XmlEnumValue("GROUND OPS - INFANTRY")
  GROUND_OPS___INFANTRY("GROUND OPS - INFANTRY"),
  @XmlEnumValue("GROUND OPS - INTELLIGENCE")
  GROUND_OPS___INTELLIGENCE("GROUND OPS - INTELLIGENCE"),
  @XmlEnumValue("GROUND OPS - INTELLIGENCE - ASAS")
  GROUND_OPS___INTELLIGENCE___ASAS("GROUND OPS - INTELLIGENCE - ASAS"),
  @XmlEnumValue("GROUND OPS - TACCS")
  GROUND_OPS___TACCS("GROUND OPS - TACCS"),
  @XmlEnumValue("GROUND OPS - TRAINING")
  GROUND_OPS___TRAINING("GROUND OPS - TRAINING"),
  @XmlEnumValue("SEA OPS")
  SEA_OPS("SEA OPS"),
  @XmlEnumValue("SEA OPS - ASW")
  SEA_OPS___ASW("SEA OPS - ASW"),
  @XmlEnumValue("SEA OPS - ASW - SONOBOUY")
  SEA_OPS___ASW___SONOBOUY("SEA OPS - ASW - SONOBOUY"),
  @XmlEnumValue("SEA OPS - ELECTRONIC WARFARE")
  SEA_OPS___ELECTRONIC_WARFARE("SEA OPS - ELECTRONIC WARFARE"),
  @XmlEnumValue("SEA OPS - FLEET SUPPORT")
  SEA_OPS___FLEET_SUPPORT("SEA OPS - FLEET SUPPORT"),
  @XmlEnumValue("SEA OPS - FORACS")
  SEA_OPS___FORACS("SEA OPS - FORACS"),
  @XmlEnumValue("SEA OPS - INTELLIGENCE")
  SEA_OPS___INTELLIGENCE("SEA OPS - INTELLIGENCE"),
  @XmlEnumValue("SEA OPS - INTELLIGENCE - TARGET")
  SEA_OPS___INTELLIGENCE___TARGET("SEA OPS - INTELLIGENCE - TARGET"),
  @XmlEnumValue("SEA OPS - NAVAIDS")
  SEA_OPS___NAVAIDS("SEA OPS - NAVAIDS"),
  @XmlEnumValue("SEA OPS - NAVAIDS - NAVIGATION RADAR")
  SEA_OPS___NAVAIDS___NAVIGATION_RADAR("SEA OPS - NAVAIDS - NAVIGATION RADAR"),
  @XmlEnumValue("SEA OPS - RESUPPLY")
  SEA_OPS___RESUPPLY("SEA OPS - RESUPPLY"),
  @XmlEnumValue("SEA OPS - SHIP/AIR OPS")
  SEA_OPS___SHIP_AIR_OPS("SEA OPS - SHIP/AIR OPS"),
  @XmlEnumValue("SEA OPS - SHIP/SHIP")
  SEA_OPS___SHIP_SHIP("SEA OPS - SHIP/SHIP"),
  @XmlEnumValue("SEA OPS - SHIP/SHIP - AEGIS")
  SEA_OPS___SHIP_SHIP___AEGIS("SEA OPS - SHIP/SHIP - AEGIS"),
  @XmlEnumValue("SEA OPS - SHIP/SHORE OPS")
  SEA_OPS___SHIP_SHORE_OPS("SEA OPS - SHIP/SHORE OPS"),
  @XmlEnumValue("SEA OPS - SHIP/SHORE OPS - HARBOR-PORT OPS")
  SEA_OPS___SHIP_SHORE_OPS___HARBOR_PORT_OPS("SEA OPS - SHIP/SHORE OPS - HARBOR-PORT OPS"),
  @XmlEnumValue("SEA OPS - SHIP/SHORE OPS - NAVAL GUNFIRE SUPPORT")
  SEA_OPS___SHIP_SHORE_OPS___NAVAL_GUNFIRE_SUPPORT("SEA OPS - SHIP/SHORE OPS - NAVAL GUNFIRE SUPPORT"),
  @XmlEnumValue("SEA OPS - TRAINING")
  SEA_OPS___TRAINING("SEA OPS - TRAINING"),
  @XmlEnumValue("SPACE OPS")
  SPACE_OPS("SPACE OPS"),
  @XmlEnumValue("SPACE OPS - EXPERIMENTAL")
  SPACE_OPS___EXPERIMENTAL("SPACE OPS - EXPERIMENTAL"),
  @XmlEnumValue("SPACE OPS - SATCOM")
  SPACE_OPS___SATCOM("SPACE OPS - SATCOM"),
  @XmlEnumValue("SPACE OPS - SATCOM - AEHF")
  SPACE_OPS___SATCOM___AEHF("SPACE OPS - SATCOM - AEHF"),
  @XmlEnumValue("SPACE OPS - SATCOM - AFSATCOM")
  SPACE_OPS___SATCOM___AFSATCOM("SPACE OPS - SATCOM - AFSATCOM"),
  @XmlEnumValue("SPACE OPS - SATCOM - DSCS")
  SPACE_OPS___SATCOM___DSCS("SPACE OPS - SATCOM - DSCS"),
  @XmlEnumValue("SPACE OPS - SATCOM - FLTSATCOM")
  SPACE_OPS___SATCOM___FLTSATCOM("SPACE OPS - SATCOM - FLTSATCOM"),
  @XmlEnumValue("SPACE OPS - SATCOM - GBS")
  SPACE_OPS___SATCOM___GBS("SPACE OPS - SATCOM - GBS"),
  @XmlEnumValue("SPACE OPS - SATCOM - LEASAT")
  SPACE_OPS___SATCOM___LEASAT("SPACE OPS - SATCOM - LEASAT"),
  @XmlEnumValue("SPACE OPS - SATCOM - Milstar")
  SPACE_OPS___SATCOM___MILSTAR("SPACE OPS - SATCOM - Milstar"),
  @XmlEnumValue("SPACE OPS - SATCOM - SPITFIRE")
  SPACE_OPS___SATCOM___SPITFIRE("SPACE OPS - SATCOM - SPITFIRE"),
  @XmlEnumValue("SPACE OPS - SATCOM - Trojan SPIRIT")
  SPACE_OPS___SATCOM___TROJAN_SPIRIT("SPACE OPS - SATCOM - Trojan SPIRIT"),
  @XmlEnumValue("SPACE OPS - SATCOM - WGS")
  SPACE_OPS___SATCOM___WGS("SPACE OPS - SATCOM - WGS"),
  @XmlEnumValue("SPACE OPS - SATCOM - UFO")
  SPACE_OPS___SATCOM___UFO("SPACE OPS - SATCOM - UFO"),
  @XmlEnumValue("SPACE OPS - GPS")
  SPACE_OPS___GPS("SPACE OPS - GPS"),
  @XmlEnumValue("SPACE OPS - METEOROLOGICAL")
  SPACE_OPS___METEOROLOGICAL("SPACE OPS - METEOROLOGICAL"),
  @XmlEnumValue("SPACE OPS - METEOROLOGICAL - DMSP")
  SPACE_OPS___METEOROLOGICAL___DMSP("SPACE OPS - METEOROLOGICAL - DMSP"),
  @XmlEnumValue("SPACE OPS - METEOROLOGICAL - SAWDS")
  SPACE_OPS___METEOROLOGICAL___SAWDS("SPACE OPS - METEOROLOGICAL - SAWDS"),
  @XmlEnumValue("SPACE OPS - NASA")
  SPACE_OPS___NASA("SPACE OPS - NASA"),
  @XmlEnumValue("SPACE OPS - NASA - SHUTTLE")
  SPACE_OPS___NASA___SHUTTLE("SPACE OPS - NASA - SHUTTLE"),
  @XmlEnumValue("RANGE OPS")
  RANGE_OPS("RANGE OPS"),
  @XmlEnumValue("RANGE OPS - EXPERIMENTAL")
  RANGE_OPS___EXPERIMENTAL("RANGE OPS - EXPERIMENTAL"),
  @XmlEnumValue("RANGE OPS - FLIGHT TEST")
  RANGE_OPS___FLIGHT_TEST("RANGE OPS - FLIGHT TEST"),
  @XmlEnumValue("RANGE OPS - RANGE CONTROL")
  RANGE_OPS___RANGE_CONTROL("RANGE OPS - RANGE CONTROL"),
  @XmlEnumValue("RANGE OPS - RANGE CONTROL - OCCS SUPPORT")
  RANGE_OPS___RANGE_CONTROL___OCCS_SUPPORT("RANGE OPS - RANGE CONTROL - OCCS SUPPORT"),
  @XmlEnumValue("RANGE OPS - RANGE CONTROL - RDMS")
  RANGE_OPS___RANGE_CONTROL___RDMS("RANGE OPS - RANGE CONTROL - RDMS"),
  @XmlEnumValue("RANGE OPS - RANGE CONTROL - TELEMETRY")
  RANGE_OPS___RANGE_CONTROL___TELEMETRY("RANGE OPS - RANGE CONTROL - TELEMETRY"),
  @XmlEnumValue("RANGE OPS - RANGE CONTROL - TRUNKING")
  RANGE_OPS___RANGE_CONTROL___TRUNKING("RANGE OPS - RANGE CONTROL - TRUNKING"),
  @XmlEnumValue("RANGE OPS - SAFETY")
  RANGE_OPS___SAFETY("RANGE OPS - SAFETY"),
  @XmlEnumValue("RANGE OPS - SIMULATOR")
  RANGE_OPS___SIMULATOR("RANGE OPS - SIMULATOR"),
  @XmlEnumValue("RANGE OPS - TEST RANGE")
  RANGE_OPS___TEST_RANGE("RANGE OPS - TEST RANGE"),
  @XmlEnumValue("RANGE OPS - TEST RANGE - TARGET")
  RANGE_OPS___TEST_RANGE___TARGET("RANGE OPS - TEST RANGE - TARGET"),
  @XmlEnumValue("RANGE OPS - TEST RANGE - TARGET SCORING")
  RANGE_OPS___TEST_RANGE___TARGET_SCORING("RANGE OPS - TEST RANGE - TARGET SCORING"),
  @XmlEnumValue("RANGE OPS - TEST RANGE - TEST RANGE TIMING")
  RANGE_OPS___TEST_RANGE___TEST_RANGE_TIMING("RANGE OPS - TEST RANGE - TEST RANGE TIMING"),
  @XmlEnumValue("RANGE OPS - TEST RANGE - TCRS")
  RANGE_OPS___TEST_RANGE___TCRS("RANGE OPS - TEST RANGE - TCRS"),
  @XmlEnumValue("RANGE OPS - TEST RANGE - TOSS")
  RANGE_OPS___TEST_RANGE___TOSS("RANGE OPS - TEST RANGE - TOSS"),
  @XmlEnumValue("RANGE OPS - TRAINING")
  RANGE_OPS___TRAINING("RANGE OPS - TRAINING"),
  @XmlEnumValue("RANGE OPS - TRAINING - MITT/DTES")
  RANGE_OPS___TRAINING___MITT_DTES("RANGE OPS - TRAINING - MITT/DTES"),
  @XmlEnumValue("SURVEILLANCE/RECONNAISSANCE")
  SURVEILLANCE_RECONNAISSANCE("SURVEILLANCE/RECONNAISSANCE"),
  @XmlEnumValue("SURVEILLANCE/RECONNAISSANCE - AIR DEFENSE WARNING")
  SURVEILLANCE_RECONNAISSANCE___AIR_DEFENSE_WARNING("SURVEILLANCE/RECONNAISSANCE - AIR DEFENSE WARNING"),
  @XmlEnumValue("SURVEILLANCE/RECONNAISSANCE - AIR DEFENSE WARNING - AWACS")
  SURVEILLANCE_RECONNAISSANCE___AIR_DEFENSE_WARNING___AWACS("SURVEILLANCE/RECONNAISSANCE - AIR DEFENSE WARNING - AWACS"),
  @XmlEnumValue("SURVEILLANCE/RECONNAISSANCE - AIR DEFENSE WARNING - BMEWS")
  SURVEILLANCE_RECONNAISSANCE___AIR_DEFENSE_WARNING___BMEWS("SURVEILLANCE/RECONNAISSANCE - AIR DEFENSE WARNING - BMEWS"),
  @XmlEnumValue("SURVEILLANCE/RECONNAISSANCE - AIR DEFENSE WARNING - CARS")
  SURVEILLANCE_RECONNAISSANCE___AIR_DEFENSE_WARNING___CARS("SURVEILLANCE/RECONNAISSANCE - AIR DEFENSE WARNING - CARS"),
  @XmlEnumValue("SURVEILLANCE/RECONNAISSANCE - AIR DEFENSE WARNING - GRCS")
  SURVEILLANCE_RECONNAISSANCE___AIR_DEFENSE_WARNING___GRCS("SURVEILLANCE/RECONNAISSANCE - AIR DEFENSE WARNING - GRCS"),
  @XmlEnumValue("SURVEILLANCE/RECONNAISSANCE - AIR DEFENSE WARNING - JSS")
  SURVEILLANCE_RECONNAISSANCE___AIR_DEFENSE_WARNING___JSS("SURVEILLANCE/RECONNAISSANCE - AIR DEFENSE WARNING - JSS"),
  @XmlEnumValue("SURVEILLANCE/RECONNAISSANCE - AIR DEFENSE WARNING - OTHR/ROTHR")
  SURVEILLANCE_RECONNAISSANCE___AIR_DEFENSE_WARNING___OTHR_ROTHR("SURVEILLANCE/RECONNAISSANCE - AIR DEFENSE WARNING - OTHR/ROTHR"),
  @XmlEnumValue("SURVEILLANCE/RECONNAISSANCE - AIR DEFENSE WARNING - PAVE PAWS")
  SURVEILLANCE_RECONNAISSANCE___AIR_DEFENSE_WARNING___PAVE_PAWS("SURVEILLANCE/RECONNAISSANCE - AIR DEFENSE WARNING - PAVE PAWS"),
  @XmlEnumValue("SURVEILLANCE/RECONNAISSANCE - TRAINING")
  SURVEILLANCE_RECONNAISSANCE___TRAINING("SURVEILLANCE/RECONNAISSANCE - TRAINING"),
  @XmlEnumValue("SPECIAL OPS")
  SPECIAL_OPS("SPECIAL OPS"),
  @XmlEnumValue("SPECIAL OPS - AIR FORCE SPECIAL OPS")
  SPECIAL_OPS___AIR_FORCE_SPECIAL_OPS("SPECIAL OPS - AIR FORCE SPECIAL OPS"),
  @XmlEnumValue("SPECIAL OPS - ARMY SPECIAL OPS")
  SPECIAL_OPS___ARMY_SPECIAL_OPS("SPECIAL OPS - ARMY SPECIAL OPS"),
  @XmlEnumValue("SPECIAL OPS - ARMY SPECIAL OPS - CIVIL AFFAIRS")
  SPECIAL_OPS___ARMY_SPECIAL_OPS___CIVIL_AFFAIRS("SPECIAL OPS - ARMY SPECIAL OPS - CIVIL AFFAIRS"),
  @XmlEnumValue("SPECIAL OPS - ARMY SPECIAL OPS - PSYCHOLOGICAL OPS")
  SPECIAL_OPS___ARMY_SPECIAL_OPS___PSYCHOLOGICAL_OPS("SPECIAL OPS - ARMY SPECIAL OPS - PSYCHOLOGICAL OPS"),
  @XmlEnumValue("SPECIAL OPS - ARMY SPECIAL OPS - RANGER UNITS")
  SPECIAL_OPS___ARMY_SPECIAL_OPS___RANGER_UNITS("SPECIAL OPS - ARMY SPECIAL OPS - RANGER UNITS"),
  @XmlEnumValue("SPECIAL OPS - ARMY SPECIAL OPS - SPECIAL FORCES")
  SPECIAL_OPS___ARMY_SPECIAL_OPS___SPECIAL_FORCES("SPECIAL OPS - ARMY SPECIAL OPS - SPECIAL FORCES"),
  @XmlEnumValue("SPECIAL OPS - NAVY SPECIAL OPS")
  SPECIAL_OPS___NAVY_SPECIAL_OPS("SPECIAL OPS - NAVY SPECIAL OPS"),
  @XmlEnumValue("C3")
  C_3("C3"),
  @XmlEnumValue("C3 - COMMAND NET")
  C_3___COMMAND_NET("C3 - COMMAND NET"),
  @XmlEnumValue("C3 - COMMAND NET - GLOBAL")
  C_3___COMMAND_NET___GLOBAL("C3 - COMMAND NET - GLOBAL"),
  @XmlEnumValue("C3 - COMMAND NET - GLOBAL ALE")
  C_3___COMMAND_NET___GLOBAL_ALE("C3 - COMMAND NET - GLOBAL ALE"),
  @XmlEnumValue("C3 - COMMAND NET - GLOBAL BLACK")
  C_3___COMMAND_NET___GLOBAL_BLACK("C3 - COMMAND NET - GLOBAL BLACK"),
  @XmlEnumValue("C3 - COMMAND NET - GLOBAL DISCRETE")
  C_3___COMMAND_NET___GLOBAL_DISCRETE("C3 - COMMAND NET - GLOBAL DISCRETE"),
  @XmlEnumValue("C3 - COMMAND NET - GLOBAL RED")
  C_3___COMMAND_NET___GLOBAL_RED("C3 - COMMAND NET - GLOBAL RED"),
  @XmlEnumValue("C3 - COMMAND NET - HICOM (High Command)")
  C_3___COMMAND_NET___HICOM__HIGH_COMMAND__("C3 - COMMAND NET - HICOM (High Command)"),
  @XmlEnumValue("C3 - DATA LINK")
  C_3___DATA_LINK("C3 - DATA LINK"),
  @XmlEnumValue("C3 - DATA LINK - ARTS (Telemetry)")
  C_3___DATA_LINK___ARTS__TELEMETRY__("C3 - DATA LINK - ARTS (Telemetry)"),
  @XmlEnumValue("C3 - DATA LINK - JTIDS/MIDS")
  C_3___DATA_LINK___JTIDS_MIDS("C3 - DATA LINK - JTIDS/MIDS"),
  @XmlEnumValue("C3 - DATA LINK - SGLS")
  C_3___DATA_LINK___SGLS("C3 - DATA LINK - SGLS"),
  @XmlEnumValue("C3 - DATA LINK - TADIL-A")
  C_3___DATA_LINK___TADIL_A("C3 - DATA LINK - TADIL-A"),
  @XmlEnumValue("C3 - DATA LINK - TADIL-C")
  C_3___DATA_LINK___TADIL_C("C3 - DATA LINK - TADIL-C"),
  @XmlEnumValue("C3 - COMMS")
  C_3___COMMS("C3 - COMMS"),
  @XmlEnumValue("C3 - COMMS - IONOSPHERIC SOUNDER")
  C_3___COMMS___IONOSPHERIC_SOUNDER("C3 - COMMS - IONOSPHERIC SOUNDER"),
  @XmlEnumValue("C3 - COMMS - ISYSCON")
  C_3___COMMS___ISYSCON("C3 - COMMS - ISYSCON"),
  @XmlEnumValue("C3 - COMMS - MARS")
  C_3___COMMS___MARS("C3 - COMMS - MARS"),
  @XmlEnumValue("C3 - COMMS - MICROWAVE")
  C_3___COMMS___MICROWAVE("C3 - COMMS - MICROWAVE"),
  @XmlEnumValue("C3 - COMMS - MSE")
  C_3___COMMS___MSE("C3 - COMMS - MSE"),
  @XmlEnumValue("C3 - COMMS - RADIO RELAY")
  C_3___COMMS___RADIO_RELAY("C3 - COMMS - RADIO RELAY"),
  @XmlEnumValue("C3 - COMMS - TACTS")
  C_3___COMMS___TACTS("C3 - COMMS - TACTS"),
  @XmlEnumValue("C3 - GCCS")
  C_3___GCCS("C3 - GCCS"),
  @XmlEnumValue("C3 - SATELLITE COMMS")
  C_3___SATELLITE_COMMS("C3 - SATELLITE COMMS"),
  @XmlEnumValue("C3 - SATELLITE COMMS - AEHF")
  C_3___SATELLITE_COMMS___AEHF("C3 - SATELLITE COMMS - AEHF"),
  @XmlEnumValue("C3 - SATELLITE COMMS - AFSATCOM")
  C_3___SATELLITE_COMMS___AFSATCOM("C3 - SATELLITE COMMS - AFSATCOM"),
  @XmlEnumValue("C3 - SATELLITE COMMS - DSCS")
  C_3___SATELLITE_COMMS___DSCS("C3 - SATELLITE COMMS - DSCS"),
  @XmlEnumValue("C3 - SATELLITE COMMS - FLTSATCOM")
  C_3___SATELLITE_COMMS___FLTSATCOM("C3 - SATELLITE COMMS - FLTSATCOM"),
  @XmlEnumValue("C3 - SATELLITE COMMS - GBS")
  C_3___SATELLITE_COMMS___GBS("C3 - SATELLITE COMMS - GBS"),
  @XmlEnumValue("C3 - SATELLITE COMMS - LEASAT")
  C_3___SATELLITE_COMMS___LEASAT("C3 - SATELLITE COMMS - LEASAT"),
  @XmlEnumValue("C3 - SATELLITE COMMS - MILSTAR")
  C_3___SATELLITE_COMMS___MILSTAR("C3 - SATELLITE COMMS - MILSTAR"),
  @XmlEnumValue("C3 - SATELLITE COMMS - SPITFIRE")
  C_3___SATELLITE_COMMS___SPITFIRE("C3 - SATELLITE COMMS - SPITFIRE"),
  @XmlEnumValue("C3 - SATELLITE COMMS - TROJAN SPIRIT")
  C_3___SATELLITE_COMMS___TROJAN_SPIRIT("C3 - SATELLITE COMMS - TROJAN SPIRIT"),
  @XmlEnumValue("C3 - SATELLITE COMMS - WGS")
  C_3___SATELLITE_COMMS___WGS("C3 - SATELLITE COMMS - WGS"),
  @XmlEnumValue("C3 - SATELLITE COMMS - UFO")
  C_3___SATELLITE_COMMS___UFO("C3 - SATELLITE COMMS - UFO"),
  @XmlEnumValue("C3 - TELEMETERY")
  C_3___TELEMETERY("C3 - TELEMETERY"),
  @XmlEnumValue("C3 - TELEMETERY - ARTS")
  C_3___TELEMETERY___ARTS("C3 - TELEMETERY - ARTS"),
  @XmlEnumValue("C3 - TELEMETERY - SGLS")
  C_3___TELEMETERY___SGLS("C3 - TELEMETERY - SGLS"),
  @XmlEnumValue("SUSTAINING OPS")
  SUSTAINING_OPS("SUSTAINING OPS"),
  @XmlEnumValue("SUSTAINING OPS - ADMINISTRATIVE")
  SUSTAINING_OPS___ADMINISTRATIVE("SUSTAINING OPS - ADMINISTRATIVE"),
  @XmlEnumValue("SUSTAINING OPS - ADMINISTRATIVE - INSTALLATION PA SYSTEM (Giant Voice)")
  SUSTAINING_OPS___ADMINISTRATIVE___INSTALLATION_PA_SYSTEM__GIANT_VOICE__("SUSTAINING OPS - ADMINISTRATIVE - INSTALLATION PA SYSTEM (Giant Voice)"),
  @XmlEnumValue("SUSTAINING OPS - ADMINISTRATIVE - PAGING")
  SUSTAINING_OPS___ADMINISTRATIVE___PAGING("SUSTAINING OPS - ADMINISTRATIVE - PAGING"),
  @XmlEnumValue("SUSTAINING OPS - ADMINISTRATIVE - TRAVELERS INFORMATION SYSTEM")
  SUSTAINING_OPS___ADMINISTRATIVE___TRAVELERS_INFORMATION_SYSTEM("SUSTAINING OPS - ADMINISTRATIVE - TRAVELERS INFORMATION SYSTEM"),
  @XmlEnumValue("SUSTAINING OPS - ADMINISTRATIVE - UNLICENSED DEVICE")
  SUSTAINING_OPS___ADMINISTRATIVE___UNLICENSED_DEVICE("SUSTAINING OPS - ADMINISTRATIVE - UNLICENSED DEVICE"),
  @XmlEnumValue("SUSTAINING OPS - ADMINISTRATIVE - WIRELESS LOCAL AREA NETWORK")
  SUSTAINING_OPS___ADMINISTRATIVE___WIRELESS_LOCAL_AREA_NETWORK("SUSTAINING OPS - ADMINISTRATIVE - WIRELESS LOCAL AREA NETWORK"),
  @XmlEnumValue("SUSTAINING OPS - ADMINISTRATIVE - WIRELESS MIKE")
  SUSTAINING_OPS___ADMINISTRATIVE___WIRELESS_MIKE("SUSTAINING OPS - ADMINISTRATIVE - WIRELESS MIKE"),
  @XmlEnumValue("SUSTAINING OPS - CIVIL ENGINEERING")
  SUSTAINING_OPS___CIVIL_ENGINEERING("SUSTAINING OPS - CIVIL ENGINEERING"),
  @XmlEnumValue("SUSTAINING OPS - CIVIL ENGINEERING - CIVIL WORKS")
  SUSTAINING_OPS___CIVIL_ENGINEERING___CIVIL_WORKS("SUSTAINING OPS - CIVIL ENGINEERING - CIVIL WORKS"),
  @XmlEnumValue("SUSTAINING OPS - CIVIL ENGINEERING - CONSTRUCTION")
  SUSTAINING_OPS___CIVIL_ENGINEERING___CONSTRUCTION("SUSTAINING OPS - CIVIL ENGINEERING - CONSTRUCTION"),
  @XmlEnumValue("SUSTAINING OPS - CIVIL ENGINEERING - INDUSTRIAL CONTROLS")
  SUSTAINING_OPS___CIVIL_ENGINEERING___INDUSTRIAL_CONTROLS("SUSTAINING OPS - CIVIL ENGINEERING - INDUSTRIAL CONTROLS"),
  @XmlEnumValue("SUSTAINING OPS - CIVIL ENGINEERING - PRIME BEEF")
  SUSTAINING_OPS___CIVIL_ENGINEERING___PRIME_BEEF("SUSTAINING OPS - CIVIL ENGINEERING - PRIME BEEF"),
  @XmlEnumValue("SUSTAINING OPS - CIVIL ENGINEERING - PUBLIC WORKS")
  SUSTAINING_OPS___CIVIL_ENGINEERING___PUBLIC_WORKS("SUSTAINING OPS - CIVIL ENGINEERING - PUBLIC WORKS"),
  @XmlEnumValue("SUSTAINING OPS - CIVIL ENGINEERING - RED HORSE")
  SUSTAINING_OPS___CIVIL_ENGINEERING___RED_HORSE("SUSTAINING OPS - CIVIL ENGINEERING - RED HORSE"),
  @XmlEnumValue("SUSTAINING OPS - CIVIL ENGINEERING - SAFETY")
  SUSTAINING_OPS___CIVIL_ENGINEERING___SAFETY("SUSTAINING OPS - CIVIL ENGINEERING - SAFETY"),
  @XmlEnumValue("SUSTAINING OPS - CIVIL ENGINEERING - SEABEES")
  SUSTAINING_OPS___CIVIL_ENGINEERING___SEABEES("SUSTAINING OPS - CIVIL ENGINEERING - SEABEES"),
  @XmlEnumValue("SUSTAINING OPS - CIVIL ENGINEERING - UTILITIES")
  SUSTAINING_OPS___CIVIL_ENGINEERING___UTILITIES("SUSTAINING OPS - CIVIL ENGINEERING - UTILITIES"),
  @XmlEnumValue("SUSTAINING OPS - COMMAND AND CONTROL")
  SUSTAINING_OPS___COMMAND_AND_CONTROL("SUSTAINING OPS - COMMAND AND CONTROL"),
  @XmlEnumValue("SUSTAINING OPS - COMMAND AND CONTROL - BASE OPS")
  SUSTAINING_OPS___COMMAND_AND_CONTROL___BASE_OPS("SUSTAINING OPS - COMMAND AND CONTROL - BASE OPS"),
  @XmlEnumValue("SUSTAINING OPS - COMMAND AND CONTROL - COMMAND NET")
  SUSTAINING_OPS___COMMAND_AND_CONTROL___COMMAND_NET("SUSTAINING OPS - COMMAND AND CONTROL - COMMAND NET"),
  @XmlEnumValue("SUSTAINING OPS - COMMAND AND CONTROL - MOMS")
  SUSTAINING_OPS___COMMAND_AND_CONTROL___MOMS("SUSTAINING OPS - COMMAND AND CONTROL - MOMS"),
  @XmlEnumValue("SUSTAINING OPS - COMMAND AND CONTROL - TRUNKING")
  SUSTAINING_OPS___COMMAND_AND_CONTROL___TRUNKING("SUSTAINING OPS - COMMAND AND CONTROL - TRUNKING"),
  @XmlEnumValue("SUSTAINING OPS - EMERGENCY SERVICES")
  SUSTAINING_OPS___EMERGENCY_SERVICES("SUSTAINING OPS - EMERGENCY SERVICES"),
  @XmlEnumValue("SUSTAINING OPS - EMERGENCY SERVICES - ALARM SYSTEMS")
  SUSTAINING_OPS___EMERGENCY_SERVICES___ALARM_SYSTEMS("SUSTAINING OPS - EMERGENCY SERVICES - ALARM SYSTEMS"),
  @XmlEnumValue("SUSTAINING OPS - EMERGENCY SERVICES - DISASTER PLANNING")
  SUSTAINING_OPS___EMERGENCY_SERVICES___DISASTER_PLANNING("SUSTAINING OPS - EMERGENCY SERVICES - DISASTER PLANNING"),
  @XmlEnumValue("SUSTAINING OPS - EMERGENCY SERVICES - EOD")
  SUSTAINING_OPS___EMERGENCY_SERVICES___EOD("SUSTAINING OPS - EMERGENCY SERVICES - EOD"),
  @XmlEnumValue("SUSTAINING OPS - EMERGENCY SERVICES - FIRE")
  SUSTAINING_OPS___EMERGENCY_SERVICES___FIRE("SUSTAINING OPS - EMERGENCY SERVICES - FIRE"),
  @XmlEnumValue("SUSTAINING OPS - EMERGENCY SERVICES - HAZMAT")
  SUSTAINING_OPS___EMERGENCY_SERVICES___HAZMAT("SUSTAINING OPS - EMERGENCY SERVICES - HAZMAT"),
  @XmlEnumValue("SUSTAINING OPS - EMERGENCY SERVICES - MEDICAL")
  SUSTAINING_OPS___EMERGENCY_SERVICES___MEDICAL("SUSTAINING OPS - EMERGENCY SERVICES - MEDICAL"),
  @XmlEnumValue("SUSTAINING OPS - EMERGENCY SERVICES - WARNING SYSTEM")
  SUSTAINING_OPS___EMERGENCY_SERVICES___WARNING_SYSTEM("SUSTAINING OPS - EMERGENCY SERVICES - WARNING SYSTEM"),
  @XmlEnumValue("SUSTAINING OPS - ENVIRONMENTAL")
  SUSTAINING_OPS___ENVIRONMENTAL("SUSTAINING OPS - ENVIRONMENTAL"),
  @XmlEnumValue("SUSTAINING OPS - ENVIRONMENTAL - RESOURCES CONSERVATION")
  SUSTAINING_OPS___ENVIRONMENTAL___RESOURCES_CONSERVATION("SUSTAINING OPS - ENVIRONMENTAL - RESOURCES CONSERVATION"),
  @XmlEnumValue("SUSTAINING OPS - LAW ENFORCEMENT")
  SUSTAINING_OPS___LAW_ENFORCEMENT("SUSTAINING OPS - LAW ENFORCEMENT"),
  @XmlEnumValue("SUSTAINING OPS - LAW ENFORCEMENT - CID")
  SUSTAINING_OPS___LAW_ENFORCEMENT___CID("SUSTAINING OPS - LAW ENFORCEMENT - CID"),
  @XmlEnumValue("SUSTAINING OPS - LAW ENFORCEMENT - DIS")
  SUSTAINING_OPS___LAW_ENFORCEMENT___DIS("SUSTAINING OPS - LAW ENFORCEMENT - DIS"),
  @XmlEnumValue("SUSTAINING OPS - LAW ENFORCEMENT - MILITARY POLICE")
  SUSTAINING_OPS___LAW_ENFORCEMENT___MILITARY_POLICE("SUSTAINING OPS - LAW ENFORCEMENT - MILITARY POLICE"),
  @XmlEnumValue("SUSTAINING OPS - LAW ENFORCEMENT - NCIS")
  SUSTAINING_OPS___LAW_ENFORCEMENT___NCIS("SUSTAINING OPS - LAW ENFORCEMENT - NCIS"),
  @XmlEnumValue("SUSTAINING OPS - LAW ENFORCEMENT - OSI")
  SUSTAINING_OPS___LAW_ENFORCEMENT___OSI("SUSTAINING OPS - LAW ENFORCEMENT - OSI"),
  @XmlEnumValue("SUSTAINING OPS - LAW ENFORCEMENT - SCOPE SHIELD")
  SUSTAINING_OPS___LAW_ENFORCEMENT___SCOPE_SHIELD("SUSTAINING OPS - LAW ENFORCEMENT - SCOPE SHIELD"),
  @XmlEnumValue("SUSTAINING OPS - LAW ENFORCEMENT - SECURITY FORCE")
  SUSTAINING_OPS___LAW_ENFORCEMENT___SECURITY_FORCE("SUSTAINING OPS - LAW ENFORCEMENT - SECURITY FORCE"),
  @XmlEnumValue("SUSTAINING OPS - LAW ENFORCEMENT - SHORE PATROL")
  SUSTAINING_OPS___LAW_ENFORCEMENT___SHORE_PATROL("SUSTAINING OPS - LAW ENFORCEMENT - SHORE PATROL"),
  @XmlEnumValue("SUSTAINING OPS - LAW ENFORCEMENT - SPEED MEASUREMENT SYSTEMS")
  SUSTAINING_OPS___LAW_ENFORCEMENT___SPEED_MEASUREMENT_SYSTEMS("SUSTAINING OPS - LAW ENFORCEMENT - SPEED MEASUREMENT SYSTEMS"),
  @XmlEnumValue("SUSTAINING OPS - LAW ENFORCEMENT - SURVEILLANCE SYSTEMS")
  SUSTAINING_OPS___LAW_ENFORCEMENT___SURVEILLANCE_SYSTEMS("SUSTAINING OPS - LAW ENFORCEMENT - SURVEILLANCE SYSTEMS"),
  @XmlEnumValue("SUSTAINING OPS - LAW ENFORCEMENT - TETHERED AEROSTAT RADAR")
  SUSTAINING_OPS___LAW_ENFORCEMENT___TETHERED_AEROSTAT_RADAR("SUSTAINING OPS - LAW ENFORCEMENT - TETHERED AEROSTAT RADAR"),
  @XmlEnumValue("SUSTAINING OPS - LAW ENFORCEMENT - WEAPONS STORAGE PROTECTION")
  SUSTAINING_OPS___LAW_ENFORCEMENT___WEAPONS_STORAGE_PROTECTION("SUSTAINING OPS - LAW ENFORCEMENT - WEAPONS STORAGE PROTECTION"),
  @XmlEnumValue("SUSTAINING OPS - MAINTENANCE")
  SUSTAINING_OPS___MAINTENANCE("SUSTAINING OPS - MAINTENANCE"),
  @XmlEnumValue("SUSTAINING OPS - MAINTENANCE - AIRCRAFT")
  SUSTAINING_OPS___MAINTENANCE___AIRCRAFT("SUSTAINING OPS - MAINTENANCE - AIRCRAFT"),
  @XmlEnumValue("SUSTAINING OPS - MAINTENANCE - COMMS")
  SUSTAINING_OPS___MAINTENANCE___COMMS("SUSTAINING OPS - MAINTENANCE - COMMS"),
  @XmlEnumValue("SUSTAINING OPS - MAINTENANCE - EQUIPMENT CHECKS")
  SUSTAINING_OPS___MAINTENANCE___EQUIPMENT_CHECKS("SUSTAINING OPS - MAINTENANCE - EQUIPMENT CHECKS"),
  @XmlEnumValue("SUSTAINING OPS - MAINTENANCE - MISSILE")
  SUSTAINING_OPS___MAINTENANCE___MISSILE("SUSTAINING OPS - MAINTENANCE - MISSILE"),
  @XmlEnumValue("SUSTAINING OPS - MAINTENANCE - MUNITIONS")
  SUSTAINING_OPS___MAINTENANCE___MUNITIONS("SUSTAINING OPS - MAINTENANCE - MUNITIONS"),
  @XmlEnumValue("SUSTAINING OPS - MAINTENANCE - RAMP CONTROL")
  SUSTAINING_OPS___MAINTENANCE___RAMP_CONTROL("SUSTAINING OPS - MAINTENANCE - RAMP CONTROL"),
  @XmlEnumValue("SUSTAINING OPS - MAINTENANCE - REMOTE CONTROL CRANE")
  SUSTAINING_OPS___MAINTENANCE___REMOTE_CONTROL_CRANE("SUSTAINING OPS - MAINTENANCE - REMOTE CONTROL CRANE"),
  @XmlEnumValue("SUSTAINING OPS - MAINTENANCE - RUNWAY ICE DETECTION SYSTEMS")
  SUSTAINING_OPS___MAINTENANCE___RUNWAY_ICE_DETECTION_SYSTEMS("SUSTAINING OPS - MAINTENANCE - RUNWAY ICE DETECTION SYSTEMS"),
  @XmlEnumValue("SUSTAINING OPS - MAINTENANCE - SNOW REMOVAL")
  SUSTAINING_OPS___MAINTENANCE___SNOW_REMOVAL("SUSTAINING OPS - MAINTENANCE - SNOW REMOVAL"),
  @XmlEnumValue("SUSTAINING OPS - METEOROLOGICAL")
  SUSTAINING_OPS___METEOROLOGICAL("SUSTAINING OPS - METEOROLOGICAL"),
  @XmlEnumValue("SUSTAINING OPS - METEOROLOGICAL - AMSS")
  SUSTAINING_OPS___METEOROLOGICAL___AMSS("SUSTAINING OPS - METEOROLOGICAL - AMSS"),
  @XmlEnumValue("SUSTAINING OPS - METEOROLOGICAL - ASOS")
  SUSTAINING_OPS___METEOROLOGICAL___ASOS("SUSTAINING OPS - METEOROLOGICAL - ASOS"),
  @XmlEnumValue("SUSTAINING OPS - METEOROLOGICAL - AWOS")
  SUSTAINING_OPS___METEOROLOGICAL___AWOS("SUSTAINING OPS - METEOROLOGICAL - AWOS"),
  @XmlEnumValue("SUSTAINING OPS - METEOROLOGICAL - GOES")
  SUSTAINING_OPS___METEOROLOGICAL___GOES("SUSTAINING OPS - METEOROLOGICAL - GOES"),
  @XmlEnumValue("SUSTAINING OPS - METEOROLOGICAL - IMETS")
  SUSTAINING_OPS___METEOROLOGICAL___IMETS("SUSTAINING OPS - METEOROLOGICAL - IMETS"),
  @XmlEnumValue("SUSTAINING OPS - METEOROLOGICAL - NEXRAD")
  SUSTAINING_OPS___METEOROLOGICAL___NEXRAD("SUSTAINING OPS - METEOROLOGICAL - NEXRAD"),
  @XmlEnumValue("SUSTAINING OPS - METEOROLOGICAL - WEATHER")
  SUSTAINING_OPS___METEOROLOGICAL___WEATHER("SUSTAINING OPS - METEOROLOGICAL - WEATHER"),
  @XmlEnumValue("SUSTAINING OPS - METEOROLOGICAL - WIND PROFILER")
  SUSTAINING_OPS___METEOROLOGICAL___WIND_PROFILER("SUSTAINING OPS - METEOROLOGICAL - WIND PROFILER"),
  @XmlEnumValue("SUSTAINING OPS - NATURAL RESOURCES")
  SUSTAINING_OPS___NATURAL_RESOURCES("SUSTAINING OPS - NATURAL RESOURCES"),
  @XmlEnumValue("SUSTAINING OPS - NATURAL RESOURCES - CONSERVATION")
  SUSTAINING_OPS___NATURAL_RESOURCES___CONSERVATION("SUSTAINING OPS - NATURAL RESOURCES - CONSERVATION"),
  @XmlEnumValue("SUSTAINING OPS - NATURAL RESOURCES - WILDLIFE PRESERVATION")
  SUSTAINING_OPS___NATURAL_RESOURCES___WILDLIFE_PRESERVATION("SUSTAINING OPS - NATURAL RESOURCES - WILDLIFE PRESERVATION"),
  @XmlEnumValue("SUSTAINING OPS - NAVAIDS CONTROLS")
  SUSTAINING_OPS___NAVAIDS_CONTROLS("SUSTAINING OPS - NAVAIDS CONTROLS"),
  @XmlEnumValue("SUSTAINING OPS - NAVAIDS CONTROLS - REMOTE BARRIER CONTROL SYSTEMS")
  SUSTAINING_OPS___NAVAIDS_CONTROLS___REMOTE_BARRIER_CONTROL_SYSTEMS("SUSTAINING OPS - NAVAIDS CONTROLS - REMOTE BARRIER CONTROL SYSTEMS"),
  @XmlEnumValue("SUSTAINING OPS - NAVAIDS CONTROLS - RUNWAY LIGHTING CONTROL")
  SUSTAINING_OPS___NAVAIDS_CONTROLS___RUNWAY_LIGHTING_CONTROL("SUSTAINING OPS - NAVAIDS CONTROLS - RUNWAY LIGHTING CONTROL"),
  @XmlEnumValue("SUSTAINING OPS - SUPPLY AND LOGISTICS")
  SUSTAINING_OPS___SUPPLY_AND_LOGISTICS("SUSTAINING OPS - SUPPLY AND LOGISTICS"),
  @XmlEnumValue("SUSTAINING OPS - SUPPLY AND LOGISTICS - AMPS")
  SUSTAINING_OPS___SUPPLY_AND_LOGISTICS___AMPS("SUSTAINING OPS - SUPPLY AND LOGISTICS - AMPS"),
  @XmlEnumValue("SUSTAINING OPS - SUPPLY AND LOGISTICS - CSSCS")
  SUSTAINING_OPS___SUPPLY_AND_LOGISTICS___CSSCS("SUSTAINING OPS - SUPPLY AND LOGISTICS - CSSCS"),
  @XmlEnumValue("SUSTAINING OPS - SUPPLY AND LOGISTICS - INVENTORY/INVENTORY CONTROLS")
  SUSTAINING_OPS___SUPPLY_AND_LOGISTICS___INVENTORY_INVENTORY_CONTROLS("SUSTAINING OPS - SUPPLY AND LOGISTICS - INVENTORY/INVENTORY CONTROLS"),
  @XmlEnumValue("SUSTAINING OPS - SUPPLY AND LOGISTICS - MTS")
  SUSTAINING_OPS___SUPPLY_AND_LOGISTICS___MTS("SUSTAINING OPS - SUPPLY AND LOGISTICS - MTS"),
  @XmlEnumValue("SUSTAINING OPS - SUPPLY AND LOGISTICS - NISTARS")
  SUSTAINING_OPS___SUPPLY_AND_LOGISTICS___NISTARS("SUSTAINING OPS - SUPPLY AND LOGISTICS - NISTARS"),
  @XmlEnumValue("SUSTAINING OPS - SUPPLY AND LOGISTICS - POL")
  SUSTAINING_OPS___SUPPLY_AND_LOGISTICS___POL("SUSTAINING OPS - SUPPLY AND LOGISTICS - POL"),
  @XmlEnumValue("SUSTAINING OPS - SUPPLY AND LOGISTICS - RESUPPLY")
  SUSTAINING_OPS___SUPPLY_AND_LOGISTICS___RESUPPLY("SUSTAINING OPS - SUPPLY AND LOGISTICS - RESUPPLY"),
  @XmlEnumValue("SUSTAINING OPS - SUPPLY AND LOGISTICS - RF TAGS")
  SUSTAINING_OPS___SUPPLY_AND_LOGISTICS___RF_TAGS("SUSTAINING OPS - SUPPLY AND LOGISTICS - RF TAGS"),
  @XmlEnumValue("SUSTAINING OPS - SUPPLY AND LOGISTICS - SHIPYARD")
  SUSTAINING_OPS___SUPPLY_AND_LOGISTICS___SHIPYARD("SUSTAINING OPS - SUPPLY AND LOGISTICS - SHIPYARD"),
  @XmlEnumValue("SUSTAINING OPS - TRAINING")
  SUSTAINING_OPS___TRAINING("SUSTAINING OPS - TRAINING"),
  @XmlEnumValue("SUSTAINING OPS - TRANSPORTATION")
  SUSTAINING_OPS___TRANSPORTATION("SUSTAINING OPS - TRANSPORTATION"),
  @XmlEnumValue("SUSTAINING OPS - TRANSPORTATION - MOTOR POOL")
  SUSTAINING_OPS___TRANSPORTATION___MOTOR_POOL("SUSTAINING OPS - TRANSPORTATION - MOTOR POOL"),
  @XmlEnumValue("SUSTAINING OPS - TRANSPORTATION - TAXI")
  SUSTAINING_OPS___TRANSPORTATION___TAXI("SUSTAINING OPS - TRANSPORTATION - TAXI"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS")
  DOMESTIC_SUPPORT_OPS("DOMESTIC SUPPORT OPS"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - COMMUNITY ASSISTANCE")
  DOMESTIC_SUPPORT_OPS___COMMUNITY_ASSISTANCE("DOMESTIC SUPPORT OPS - COMMUNITY ASSISTANCE"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - COMMUNITY ASSISTANCE - AERO CLUB")
  DOMESTIC_SUPPORT_OPS___COMMUNITY_ASSISTANCE___AERO_CLUB("DOMESTIC SUPPORT OPS - COMMUNITY ASSISTANCE - AERO CLUB"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - COMMUNITY ASSISTANCE - COLOR/HONOR GUARD")
  DOMESTIC_SUPPORT_OPS___COMMUNITY_ASSISTANCE___COLOR_HONOR_GUARD("DOMESTIC SUPPORT OPS - COMMUNITY ASSISTANCE - COLOR/HONOR GUARD"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - COMMUNITY ASSISTANCE - EDUCATION")
  DOMESTIC_SUPPORT_OPS___COMMUNITY_ASSISTANCE___EDUCATION("DOMESTIC SUPPORT OPS - COMMUNITY ASSISTANCE - EDUCATION"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - COMMUNITY ASSISTANCE - MUTUAL AID")
  DOMESTIC_SUPPORT_OPS___COMMUNITY_ASSISTANCE___MUTUAL_AID("DOMESTIC SUPPORT OPS - COMMUNITY ASSISTANCE - MUTUAL AID"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - COMMUNITY ASSISTANCE - PUBLIC WORKS")
  DOMESTIC_SUPPORT_OPS___COMMUNITY_ASSISTANCE___PUBLIC_WORKS("DOMESTIC SUPPORT OPS - COMMUNITY ASSISTANCE - PUBLIC WORKS"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - COMMUNITY ASSISTANCE - TRAINING")
  DOMESTIC_SUPPORT_OPS___COMMUNITY_ASSISTANCE___TRAINING("DOMESTIC SUPPORT OPS - COMMUNITY ASSISTANCE - TRAINING"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - CONTINGENCY")
  DOMESTIC_SUPPORT_OPS___CONTINGENCY("DOMESTIC SUPPORT OPS - CONTINGENCY"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - CONSEQUENCE MANAGEMENT")
  DOMESTIC_SUPPORT_OPS___CONSEQUENCE_MANAGEMENT("DOMESTIC SUPPORT OPS - CONSEQUENCE MANAGEMENT"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - CONSEQUENCE MANAGEMENT - CBR")
  DOMESTIC_SUPPORT_OPS___CONSEQUENCE_MANAGEMENT___CBR("DOMESTIC SUPPORT OPS - CONSEQUENCE MANAGEMENT - CBR"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - CONSEQUENCE MANAGEMENT - CIVIL SUPPORT TEAM")
  DOMESTIC_SUPPORT_OPS___CONSEQUENCE_MANAGEMENT___CIVIL_SUPPORT_TEAM("DOMESTIC SUPPORT OPS - CONSEQUENCE MANAGEMENT - CIVIL SUPPORT TEAM"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - CONSEQUENCE MANAGEMENT - ENVIRONMENTAL CLEANUP")
  DOMESTIC_SUPPORT_OPS___CONSEQUENCE_MANAGEMENT___ENVIRONMENTAL_CLEANUP("DOMESTIC SUPPORT OPS - CONSEQUENCE MANAGEMENT - ENVIRONMENTAL CLEANUP"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - CONSEQUENCE MANAGEMENT - FEMA")
  DOMESTIC_SUPPORT_OPS___CONSEQUENCE_MANAGEMENT___FEMA("DOMESTIC SUPPORT OPS - CONSEQUENCE MANAGEMENT - FEMA"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - CONSEQUENCE MANAGEMENT - HAZARDOUS MATERIAL RELEASE")
  DOMESTIC_SUPPORT_OPS___CONSEQUENCE_MANAGEMENT___HAZARDOUS_MATERIAL_RELEASE("DOMESTIC SUPPORT OPS - CONSEQUENCE MANAGEMENT - HAZARDOUS MATERIAL RELEASE"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - CONSEQUENCE MANAGEMENT - TECHNICAL ESCORT UNIT")
  DOMESTIC_SUPPORT_OPS___CONSEQUENCE_MANAGEMENT___TECHNICAL_ESCORT_UNIT("DOMESTIC SUPPORT OPS - CONSEQUENCE MANAGEMENT - TECHNICAL ESCORT UNIT"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - CONSEQUENCE MANAGEMENT - TRAINING")
  DOMESTIC_SUPPORT_OPS___CONSEQUENCE_MANAGEMENT___TRAINING("DOMESTIC SUPPORT OPS - CONSEQUENCE MANAGEMENT - TRAINING"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - LAW ENFORCEMENT")
  DOMESTIC_SUPPORT_OPS___LAW_ENFORCEMENT("DOMESTIC SUPPORT OPS - LAW ENFORCEMENT"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - LAW ENFORCEMENT - ANTI-TERRORISM")
  DOMESTIC_SUPPORT_OPS___LAW_ENFORCEMENT___ANTI_TERRORISM("DOMESTIC SUPPORT OPS - LAW ENFORCEMENT - ANTI-TERRORISM"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - LAW ENFORCEMENT - CIVIL DISTURBANCES")
  DOMESTIC_SUPPORT_OPS___LAW_ENFORCEMENT___CIVIL_DISTURBANCES("DOMESTIC SUPPORT OPS - LAW ENFORCEMENT - CIVIL DISTURBANCES"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - LAW ENFORCEMENT - COUNTER DRUG")
  DOMESTIC_SUPPORT_OPS___LAW_ENFORCEMENT___COUNTER_DRUG("DOMESTIC SUPPORT OPS - LAW ENFORCEMENT - COUNTER DRUG"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - LAW ENFORCEMENT - PROJECT COTHEN")
  DOMESTIC_SUPPORT_OPS___LAW_ENFORCEMENT___PROJECT_COTHEN("DOMESTIC SUPPORT OPS - LAW ENFORCEMENT - PROJECT COTHEN"),
  @XmlEnumValue("DOMESTIC SUPPORT OPS - LAW ENFORCEMENT - SPECIAL SECURITY OPS")
  DOMESTIC_SUPPORT_OPS___LAW_ENFORCEMENT___SPECIAL_SECURITY_OPS("DOMESTIC SUPPORT OPS - LAW ENFORCEMENT - SPECIAL SECURITY OPS"),
  @XmlEnumValue("OTHER OPS - LAW ENFORCEMENT")
  OTHER_OPS___LAW_ENFORCEMENT("OTHER OPS - LAW ENFORCEMENT"),
  @XmlEnumValue("OTHER OPS - LAW ENFORCEMENT - DTSS")
  OTHER_OPS___LAW_ENFORCEMENT___DTSS("OTHER OPS - LAW ENFORCEMENT - DTSS"),
  @XmlEnumValue("OTHER OPS - LAW ENFORCEMENT - ETRAC")
  OTHER_OPS___LAW_ENFORCEMENT___ETRAC("OTHER OPS - LAW ENFORCEMENT - ETRAC"),
  @XmlEnumValue("OTHER OPS - LAW ENFORCEMENT - RDTE SUPPORT")
  OTHER_OPS___LAW_ENFORCEMENT___RDTE_SUPPORT("OTHER OPS - LAW ENFORCEMENT - RDTE SUPPORT"),
  @XmlEnumValue("OTHER OPS - EXERCISE")
  OTHER_OPS___EXERCISE("OTHER OPS - EXERCISE"),
  @XmlEnumValue("OTHER OPS - EXPERIMENTAL")
  OTHER_OPS___EXPERIMENTAL("OTHER OPS - EXPERIMENTAL"),
  @XmlEnumValue("OTHER OPS - HYDROLOGIC")
  OTHER_OPS___HYDROLOGIC("OTHER OPS - HYDROLOGIC"),
  @XmlEnumValue("OTHER OPS - HYDROLOGIC - LOCKS AND DAMS")
  OTHER_OPS___HYDROLOGIC___LOCKS_AND_DAMS("OTHER OPS - HYDROLOGIC - LOCKS AND DAMS"),
  @XmlEnumValue("OTHER OPS - SEARCH AND RESCUE")
  OTHER_OPS___SEARCH_AND_RESCUE("OTHER OPS - SEARCH AND RESCUE"),
  @XmlEnumValue("OTHER OPS - SEARCH AND RESCUE - CAP")
  OTHER_OPS___SEARCH_AND_RESCUE___CAP("OTHER OPS - SEARCH AND RESCUE - CAP"),
  @XmlEnumValue("OTHER OPS - SEISMIC")
  OTHER_OPS___SEISMIC("OTHER OPS - SEISMIC"),
  @XmlEnumValue("OTHER OPS - SPECIAL COURIER")
  OTHER_OPS___SPECIAL_COURIER("OTHER OPS - SPECIAL COURIER"),
  @XmlEnumValue("OTHER OPS - SPECIAL PROJECTS")
  OTHER_OPS___SPECIAL_PROJECTS("OTHER OPS - SPECIAL PROJECTS"),
  @XmlEnumValue("OTHER OPS - SPECIAL PROJECTS - HAARP")
  OTHER_OPS___SPECIAL_PROJECTS___HAARP("OTHER OPS - SPECIAL PROJECTS - HAARP"),
  @XmlEnumValue("OTHER OPS - SURVEY")
  OTHER_OPS___SURVEY("OTHER OPS - SURVEY"),
  @XmlEnumValue("OTHER OPS - TEST AND MEASUREMENT")
  OTHER_OPS___TEST_AND_MEASUREMENT("OTHER OPS - TEST AND MEASUREMENT");
  private final String value;

  ListCFN(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static ListCFN fromValue(String v) {
    for (ListCFN c : ListCFN.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }

}
